name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
    - title: '🚀 Features'
      labels:
          - 'feature'
          - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
          - 'fix'
          - 'bug'
    - title: '🔧 Maintenance'
      label: 'maintenance'
    - title: '🧪 Test'
      label: 'test'
    - title: '🧪 Documentation'
      label: 'docs'
    - title: '📌 Dependencies'
      label: 'dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
branches:
    - develop
exclude-labels:
    - 'skip-changelog'
template: |
    $CHANGES
