language: node_js
node_js:
  - "8"
jobs:
  include:
    - stage: test
      script: npm test
    - stage: build docker image
      if: branch IN (master, develop)
      services:
      - docker
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t securecodebox/nmap:oss .
      - docker images
      - docker push securecodebox/nmap:oss