language: node_js
node_js:
  - "8"
jobs:
  include:
    - stage: test
      script: npm test
    - stage: build docker image
      if: branch IN (master, develop) AND type NOT pull_request
      services:
      - docker
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t securecodebox/nmap:oss --build-arg=COMMIT_ID=$TRAVIS_COMMIT --build-arg=BRANCH=$TRAVIS_BRANCH --build-arg=REPOSITORY_URL="https://github.com/secureCodeBox/scanner-infrastructure-nmap" .
      - docker images
      - docker push securecodebox/nmap:oss